### PR TITLE
Add datadog APM instrumentation

### PR DESCRIPTION
**Pull request by benfain**
This instruments CA for Datadog APM and adds tracing support to a few of the main functions.

Followed [DD's go instrumentation docs](https://app.datadoghq.com/apm/service-setup?architecture=container-based&collection=Helm%20Chart%20%28Recommended%29&environment=kubernetes&framework=Net%2FHTTP&language=go&profiling=false) initially among other web services.

The purpose of this is to get better visibility into what's slowing down in CA during periods of heavy scaling activity. We do have various duration metrics. being generated which give a broad picture on what might be slowing down but we want more details. To start, we traced CA operations that map to the metrics in the link above, as defined in [metrics.go](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/metrics/metrics.go#L92) (minus a few legacy and seemingly unused ones).

Traces are coming in, the separate spans are visible in the span list tab for each trace.

We realized while doing this that we may actually just need profiling for now, rather than adding spans for every single call/function. We are working on that separately, and I believe you can have traces link to profile code blocks so it may be helpful regardless.

### CODE REVIEW

**Review by philnielsen — APPROVED** [review]
LGTM

**Comment by evin-bz** [comment]
Looks great! do y'all have any traces links to look at?

**Comment by philnielsen** [comment]
@evin-bz https://app.datadoghq.com/apm/traces?query=@_top_level:1%20env:t-usw-2%20&cols=core_service,core_resource_name,log_duration,log_http.method,log_http.status_code&graphType=flamegraph&historicalData=false&messageDisplay=inline&shouldShowLegend=true&sort=time&spanID=5647036207450594972&spanType=service-entry&timeHint=1685998265662&trace=56470362074505949725647036207450594972&traceID=5647036207450594972&start=1685997386339&end=1685998286339&paused=false

**Comment by philnielsen** [comment]
see DD link in slack

**Review by salmanb — APPROVED** [review]

**Pull request merged**
